version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail
    volumes:
      # - C:\\Programming\\HR_4Sem\\metrics_analyser\\log:/var/log
      - ./config:/etc/promtail
    command: -config.file=/etc/promtail/promtail_config.yml
    networks:
      - loki
