{
 "title": "[Prototype] Applikations Monitoring (Level 3)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "up" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Available - History",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{instance=\"https://hr-ideascape-dev.app.corpintra.net/structurecube/#/\"}",
     "legendFormat": "Structure Cube Dev"
    },
    {
     "expr": "up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\"}",
     "legendFormat": "Structure Cube Int"
    },
    {
     "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}",
     "legendFormat": "Structure Cube Prod"
    },
    {
     "expr": "up{instance=\"google.com\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{instance=\"prometheus.io\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Auslastung (Int DEV DB)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "CPU Auslastung Total"
    }
   ]
  },
  {
   "title": "CPU Auslastung (Int DEV DB)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "CPU Auslastung Total"
    }
   ]
  },
  {
   "title": "CPU Auslastung (Int DEV APP)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Arbeitsspeicher Auslastung (Int DEV APP)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Arbeitsspeicher Auslastung (Int DEV APP)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Arbeitsspeicher Auslastung (Int DEV APP)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  { "title": "Netzwerk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Gesamtzeit Beantwortung HTTP-Anfragen ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_duration_seconds{})by(instance) ",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Zeitdauer  von HTTP-Anfragen  nach Phasen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Erfolgsrate HTTP-Anfragen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count(probe_success{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})/count(probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})*100",
     "legendFormat": "Structure Cube"
    },
    {
     "expr": "count(probe_success{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})/count(probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})*100",
     "legendFormat": "Committee Tool"
    }
   ]
  },
  {
   "title": "Netzwerk Geschwindigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
     "legendFormat": "DB Server: {{device}}"
    },
    {
     "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
     "legendFormat": "APP Server: {{device}}"
    },
    {
     "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
     "legendFormat": "WEB Server: : {{device}}"
    }
   ]
  },
  { "title": "Festplattenspeicher ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Speicherauslastung (Int DEV DB)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Speicherauslastung (Int DEV APP)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Speicherauslastung (Int DEV WEB)",
   "type": "timeseries",
   "description": "Speicherauslastung des Internal DEV DB Servers ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Neo4j Datenbanksystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Verfügbarer Buffer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Transaktionsrate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Heap Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    }
   ]
  },
  {
   "title": "Postgre Datenbanksystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    }
   ]
  },
  {
   "title": "Weitere Informationen und Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Informationen",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "options": {
    "content": "# IDEAScape \r\n## Ressourcenverbrauch und Performance \r\n## (Internal DEV Servers)\r\n\r\n<br> Author: Andreas Weber\r\n<br> Author: HR ITP/S\r\n<br> Copyright (c) 2021 Mercedes-Benz AG\r\n"
   }
  },
  { "title": "Weitere Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 } }
 ]
}