{
 "title": "[Prototype] Applikations Monitoring (Level 2)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "up" } }
  ]
 },
 "panels": [
  {
   "title": "Status History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Structure Cube - WEB Server Verfügbarkeit",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape-dev.app.corpintra.net/structurecube/#/\"}",
       "legendFormat": "Internal WEB Dev"
      },
      {
       "expr": "up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\"}",
       "legendFormat": "Internal WEB Int"
      },
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}",
       "legendFormat": "Internal WEB Prod"
      }
     ]
    },
    {
     "title": "Committee Tool - WEB Server Verfügbarkeit",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape-dev.app.corpintra.net/committee\"}",
       "legendFormat": "Internal WEB Dev"
      },
      {
       "expr": "up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\"}",
       "legendFormat": "Internal WEB Int"
      },
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/committee\"}",
       "legendFormat": "Internal WEB Prod"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
     "options": {
      "content": "\r\n# <center>Structure Cube</center>"
     }
    },
    {
     "title": "Structure Cube (Internal WEB Prod)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Structure Cube (Internal WEB Prod)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Structure Cube",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Structure Cube (Last 24h) (Internal WEB Prod)",
     "type": "stat",
     "description": "Structure Cube Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}[1d])* 86400"
      }
     ]
    },
    {
     "title": "Structure Cube (Internal WEB Int)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Structure Cube (Internal WEB Int)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Structure Cube",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Structure Cube (Last 24h) (Internal WEB Int)",
     "type": "stat",
     "description": "Structure Cube Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape-int.app.corpintra.net/structurecube/#/\"}[1d])* 86400"
      }
     ]
    },
    {
     "title": "Structure Cube (Internal WEB Dev)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Structure Cube (Internal WEB Dev)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit $instance über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Structure Cube",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Structure Cube (Last 24h) (Internal WEB Dev)",
     "type": "stat",
     "description": "Structure Cube Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape-dev.app.corpintra.net/structurecube/#/\"}[1d])* 86400"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "\r\n# <center>Committee Tool</center>"
     }
    },
    {
     "title": "Committee Tool  (Internal WEB Prod)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/committee\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Committee Tool  (Internal WEB Prod)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape.app.corpintra.net/committee\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/committee\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Committee Tool (Internal WEB Prod)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/committee\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Committee Tool  (Last 24h) (Internal WEB Prod)",
     "type": "stat",
     "description": "Committee Tool  Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/committee\"}[1d])*86400"
      }
     ]
    },
    {
     "title": "Committee Tool (Internal WEB Int)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/committee\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Committee Tool  (Internal WEB Prod)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Committee Tool (Internal WEB Int)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Committee Tool (Last 24h) (Internal WEB Int)",
     "type": "stat",
     "description": "Committee Tool Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\"}[1d])* 86400"
      }
     ]
    },
    {
     "title": "Committee Tool (Internal WEB Dev)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Verfügbarkeit Committee Tool (Internal WEB Prod)",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit über einen Tag",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape-int.app.corpintra.net/committee\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
      }
     ]
    },
    {
     "title": "HTTP Status Code Committee Tool (Internal WEB Dev)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://hr-ideascape-dev.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Uptime Committee Tool (Last 24h) (Internal WEB Dev)",
     "type": "stat",
     "description": "Committee Tool Uptime last 24h",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{instance=\"https://hr-ideascape-dev.app.corpintra.net/committee\"}[1d])* 86400"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Auslastung (Int DEV DB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
       "legendFormat": "CPU Auslastung Total"
      }
     ]
    },
    {
     "title": "CPU Auslastung (Int DEV WEB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
       "legendFormat": "CPU Auslastung Total"
      }
     ]
    },
    {
     "title": "CPU Auslastung (Int DEV APP)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])  * 100)) ",
       "legendFormat": "Speicherauslastung: {{instance}}"
      }
     ]
    },
    {
     "title": "Arbeitsspeicher Auslastung (Int DEV DB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher .- Gesamt"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"} - (node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"} + node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Verbraucht"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Verfügbar"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Cached"
      },
      {
       "expr": " node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Puffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_SwapFree_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Swapped"
      }
     ]
    },
    {
     "title": "Arbeitsspeicher Auslastung (Int DEV WEB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher .- Gesamt"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"} - (node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"} + node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Verbraucht"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Verfügbar"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Cached"
      },
      {
       "expr": " node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Puffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_SwapFree_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Swapped"
      }
     ]
    },
    {
     "title": "Arbeitsspeicher Auslastung (Int DEV APP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher .- Gesamt"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"} - (node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"} + node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Verbraucht"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Verfügbar"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Cached"
      },
      {
       "expr": " node_memory_Buffers_bytes{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "Arbeitsspeicher - Puffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_SwapFree_bytes{instance=\"172.17.0.1:9100\"})",
       "legendFormat": "Arbeitsspeicher - Swapped"
      }
     ]
    }
   ]
  },
  {
   "title": "Netzwerk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gesamtzeit Beantwortung HTTP-Anfragen ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(probe_duration_seconds{})by(instance) ",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Zeitdauer  von HTTP-Anfragen  nach Phasen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Erfolgsrate HTTP-Anfragen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "count(probe_success{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})/count(probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})*100",
       "legendFormat": "Structure Cube"
      },
      {
       "expr": "count(probe_success{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})/count(probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})*100",
       "legendFormat": "Committee Tool"
      }
     ]
    },
    {
     "title": "Netzwerk Geschwindigkeit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "DB Server: {{device}}"
      },
      {
       "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "APP Server: {{device}}"
      },
      {
       "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "WEB Server: : {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Festplattenspeicher ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speicherauslastung (Int DEV DB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
       "legendFormat": "Speicherauslastung: {{instance}}"
      }
     ]
    },
    {
     "title": "Speicherauslastung (Int DEV APP)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
       "legendFormat": "Speicherauslastung: {{instance}}"
      }
     ]
    },
    {
     "title": "Speicherauslastung (Int DEV WEB)",
     "type": "timeseries",
     "description": "Speicherauslastung des Internal DEV DB Servers ",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
       "legendFormat": "Speicherauslastung: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neo4j Datenbanksystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Structure Cube"
      },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"host.docker.internal:2004\"})\n      or\n    (0 * sum_over_time(up{instance=\"host.docker.internal:2004\"}[$__interval]))\n  )[5m:$__interval]\n)*100",
       "legendFormat": "Structure Cube"
      },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Gesamtspeicher Datenbanksystem",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "neo4j_neo4j_store_size_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Structure Cube"
      },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Gesamtspeicher Datenbank",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "neo4j_neo4j_store_size_database{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Structure Cube"
      },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Verfügbar" },
      { "legendFormat": "Verwendet" }
     ]
    },
    {
     "title": "Heap Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "neo4j_vm_memory_pool_g1_eden_space{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Gesamt"
      },
      {
       "expr": "neo4j_vm_memory_pool_g1_old_gen{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Old Gen"
      },
      {
       "expr": "neo4j_vm_memory_pool_g1_eden_space{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Eden Space"
      }
     ]
    },
    {
     "title": "Buffer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "neo4j_vm_memory_buffer_direct_used{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "Buffer Nutzung"
      },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Transaktionsrate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(neo4j_neo4j_transaction_committed_read_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
       "legendFormat": "Lese Transaktionen"
      },
      {
       "expr": "rate(neo4j_neo4j_transaction_committed_write_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
       "legendFormat": "Schreib Transaktionen"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgre Datenbanksystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    },
    {
     "title": "Verfügbarer Physischer Speicher",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "legendFormat": "Structure Cube" },
      { "legendFormat": "Committee Tool" }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vollständige Logs (Int DEV APP)",
     "type": "logs",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "{agent=\"promtail\"}"
      }
     ]
    },
    {
     "title": "Fehler Logs (Int DEV APP)",
     "type": "logs",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "{agent=\"promtail\" }  |~ \"(?i)error\""
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 112 },
     "options": {
      "content": "# Gliederung nach Structure Cube und Committee Tool"
     }
    },
    {
     "title": "Vollständige Logs (Int DEV APP)",
     "type": "logs",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "{agent=\"promtail\"} |~ \"(src.DataExporter).*\""
      }
     ]
    }
   ]
  },
  {
   "title": "Alarmierungen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarmierungsverlauf",
     "type": "graph",
     "description": "Zeigt den Verlauf der Alarmierungen an",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Firing (-)   /  Pending (+)  " }
     ],
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\"}",
       "legendFormat": "{{alertname}} {{instance}} {{alertstate}} {{datacenter}}"
      },
      { "expr": "1", "legendFormat": "help_series_x_axes_in_center" },
      {
       "expr": "ALERTS{alertstate=\"pending\"}",
       "legendFormat": "{{alertname}} {{instance}} {{alertstate}} {{datacenter}}"
      }
     ]
    },
    {
     "title": "Status der Alarmierungen",
     "type": "table",
     "description": "Zeigt Anzahl der ausgelösten Alerts",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes( ALERTS_FOR_STATE[$__range] ) + 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Auslastung Monitoring Server",
     "type": "gauge",
     "description": "Durchschnittliche Verfügbarkeit $instance über eine Stunde",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])  * 100) ) "
      }
     ]
    },
    {
     "title": "Arbeitsspeicher Auslastung Monitoring Server",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"172.17.0.1:9100\"}) / (node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"} )) * 100"
      }
     ]
    },
    {
     "title": "Verwendeter Festplattenspeicher Monitoring Server",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " 100 - (sum by (instance) (node_filesystem_avail_bytes{instance=\"172.17.0.1:9100\",device!~'rootfs'}) / sum by (instance) (node_filesystem_size_bytes{instance=\"172.17.0.1:9100\",device!~'rootfs'})*100)"
      },
      {}
     ]
    },
    {
     "title": "HTTP Leseabfragen",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(prometheus_http_requests_total{instance=\"prometheus\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Weitere Informationen und Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Informationen",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": {
    "content": "# IDEAScape \r\n## Ressourcenverbrauch und Performance \r\n## (Internal DEV Servers)\r\n\r\n<br> Author: Andreas Weber\r\n<br> Author: HR ITP/S\r\n<br> Copyright (c) 2021 Mercedes-Benz AG\r\n"
   }
  },
  { "title": "Weitere Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 } }
 ]
}