{
 "title": "[PROTOTYPE] Applikations-Monitoring 2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Select Application",
    "query": "Structure Cube\n, Committee Tool"
   },
   { "name": "instance", "label": "Select Application", "query": { "query": "up{}" } },
   { "name": "job", "label": "job", "query": { "query": "up{}" } },
   {
    "name": "priority",
    "label": "Priority",
    "query": "Level 1 - Developer, Level 2 - PO / Admin, Level 3 - Lead"
   }
  ]
 },
 "panels": [
  { "title": "Structure Cube - Verfügbarkeit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$application",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Durchschnittliche Verfügbarkeit $instance ",
   "type": "gauge",
   "description": "Durchschnittliche Verfügbarkeit $instance über eine Stunde",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
    }
   ]
  },
  {
   "title": "HTTP Status Code $instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$instance\", job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Uptime $instance last 24h",
   "type": "stat",
   "description": "Structure Cube Uptime Percentage",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$instance\"}[24h])"
    }
   ]
  },
  {
   "title": "Structure Cube- Allgemeine Server Statistiken",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "CPU Cores Node Exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"172.17.0.1:9100\"})by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Auslastung Node Exporter",
   "type": "gauge",
   "description": "Structure Cube Absolut Server Uptime (Node Exporter used)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.17.0.1:9100\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"172.17.0.1:9100\"}[$__rate_interval]))))*100 ) / count(count(node_cpu_seconds_total{instance=\"172.17.0.1:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Swap Memory Total",
   "type": "stat",
   "description": "Node Exporter",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"172.17.0.1:9100\"}"
    }
   ]
  },
  {
   "title": "Swap Memory Total",
   "type": "stat",
   "description": "Node Exporter",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"172.17.0.1:9100\"}"
    }
   ]
  },
  {
   "title": "Server Uptime Nodeexporter",
   "type": "stat",
   "description": "Structure Cube Absolut Server Uptime (Node Exporter used)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"172.17.0.1:9100\"} - node_boot_time_seconds{instance=\"172.17.0.1:9100\"}"
    }
   ]
  },
  { "title": "Fehler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Success Rate over Time Structure Cube",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count(probe_success{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})/count(probe_http_status_code{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})*100",
     "legendFormat": "{{count}}"
    }
   ]
  },
  {
   "title": "HTTP Errors Count Structure Cube",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{status!~\"4..\"})"
    }
   ]
  },
  {
   "title": "Latenz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Time",
     "type": "timeseries",
     "description": "Durchschnittliche CPU Zeit über die letzten 60 Sekunden",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Netzwerk Traffic",
     "type": "timeseries",
     "description": "Netzwerk Traffic in Pakete pro Sekunde",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=\"172.17.0.1:9100\"}[$__rate_interval])",
       "legendFormat": "receive: {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "transmit: {{device}}"
      }
     ]
    },
    {
     "title": "Netzwerk Geschwindigkeit",
     "type": "timeseries",
     "description": "Netzwerk Geschwindigkeit",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "packets" } },
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=\"172.17.0.1:9100\"}",
       "legendFormat": "receive: {{device}}"
      }
     ]
    },
    {
     "title": "Netzwerk Geschwindigkeit",
     "type": "timeseries",
     "description": "Netzwerk Geschwindigkeit",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=\"$instance\"}",
       "legendFormat": "receive: {{device}}"
      }
     ]
    },
    {
     "title": "HTTP Total Request Duration Structure Cube in Comparison",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(probe_duration_seconds{})by(instance) ",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Durchschnittliche Response Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})",
       "legendFormat": "probe time structure cube"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Auslastung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gesamt CPU Auslastung",
     "type": "timeseries",
     "description": "Durchschnittliche CPU Auslastung über die letzten 60 Sekunden",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])  * 100) ) ",
       "legendFormat": "CPU Auslastung"
      }
     ]
    },
    {
     "title": "Gesamt CPU Auslastung",
     "type": "timeseries",
     "description": "Durchschnittliche CPU Auslastung über die letzten 60 Sekunden",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])  * 100) ) ",
       "legendFormat": "CPU Auslastung"
      }
     ]
    },
    {
     "title": "Zeit von aktiven CPU Processen",
     "type": "timeseries",
     "description": "Netzwerk Geschwindigkeit",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_schedstat_running_seconds_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "cpu {{cpu}} running"
      }
     ]
    },
    {
     "title": "Zeit von wartenden CPU Processen",
     "type": "timeseries",
     "description": "Netzwerk Geschwindigkeit",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_schedstat_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "cpu {{cpu}} waiting"
      }
     ]
    },
    {
     "title": "Anzahl aktiver / blockierter Prozesse",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "processes" } },
     "targets": [
      {
       "expr": "node_procs_running{instance=\"$instance\"}",
       "legendFormat": "aktive processe"
      },
      {
       "expr": "node_procs_blocked{instance=\"$instance\"}",
       "legendFormat": "blockierte processe"
      }
     ]
    }
   ]
  },
  { "title": "Speicherauslastung Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Speicherauslastung",
   "type": "timeseries",
   "description": "Speicherauslastung des Servers ",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((avg_over_time(node_memory_MemFree_bytes[$__interval]) + avg_over_time(node_memory_Cached_bytes[$__interval]) + avg_over_time(node_memory_Buffers_bytes[$__interval])) / avg_over_time(node_memory_MemTotal_bytes[$__interval])))*100",
     "legendFormat": "Speicherauslastung: {{instance}}"
    }
   ]
  },
  {
   "title": "Verfügbarer Speicher",
   "type": "timeseries",
   "description": "Verfügbarer Speicher in Bytes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes[$__interval])",
     "legendFormat": "Freier Speicher: {{instance}}"
    }
   ]
  },
  {
   "title": "Leserate Festplatte",
   "type": "timeseries",
   "description": "Leserate Festplatte",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Schreibrate Festplatte",
   "type": "timeseries",
   "description": "Schreibrate Festplatte\nsda: erste SCSI-Festplatte;\nsdb: zweite SCSI-Festplatte",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "device: {{device}}"
    }
   ]
  },
  { "title": "Neo4j - Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$application",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}"
    }
   ]
  },
  {
   "title": "Durchschnittliche Verfügbarkeit $instance ",
   "type": "gauge",
   "description": "Durchschnittliche Verfügbarkeit $instance über eine Stunde",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"})\n      or\n    (0 * sum_over_time(up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\", job=\"blackbox\"}[$__interval]))\n  )[1h:$__interval]\n)*100"
    }
   ]
  },
  {
   "title": "Node Createion Speed (ids)",
   "type": "gauge",
   "description": "Change in Neo4j ids",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(neo4j_neo4j_ids_in_use_node{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])"
    }
   ]
  },
  {
   "title": "ID Counter",
   "type": "timeseries",
   "description": "Change in Neo4j ids",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ids" } },
   "targets": [
    {
     "expr": "neo4j_neo4j_ids_in_use_node{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}"
    }
   ]
  },
  { "title": "Neo4j - Nutzung Ids", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Neo4j ids in use",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_neo4j_ids_in_use_(node|property|relationship)\", job=\"Neo4j-prometheus\", instance=~\"host.docker.internal:2004\"}, \"label\", \"$1\", \"__name__\", \"neo4j_ids_in_use_(.+)\")",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Id Rate ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(neo4j_neo4j_ids_in_use_node{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
     "legendFormat": "node rate"
    },
    {
     "expr": "rate(neo4j_neo4j_ids_in_use_property{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
     "legendFormat": "property rate"
    },
    {
     "expr": "rate(neo4j_neo4j_ids_in_use_relationship{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
     "legendFormat": "relationship rate"
    }
   ]
  },
  { "title": "Neo4j - Transaktionen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Transaktionen",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "transactions" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_neo4j_transaction_(committed|rollbacks)_total\", job=\"Neo4j-prometheus\", instance=\"host.docker.internal:2004\"}, \"label\", \"$1\", \"__name__\", \"neo4j_neo4j_transaction_(.+)\")",
     "legendFormat": "{{label}}"
    },
    { "expr": "neo4j_neo4j_transaction_" }
   ]
  },
  {
   "title": "Gesamte Transaktionsrate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(neo4j_neo4j_transaction_committed_read_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
     "legendFormat": "Read Transaktionen"
    },
    {
     "expr": "rate(neo4j_neo4j_transaction_committed_write_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}[$__interval])",
     "legendFormat": "Write Transaktionen"
    }
   ]
  },
  {
   "title": "Durchgeführte Lesetransaktionen",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "transactions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_neo4j_transaction_committed_read_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}"
    }
   ]
  },
  {
   "title": "Durchgeführte Schreibtransaktionen",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "transactions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_neo4j_transaction_committed_write_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}"
    }
   ]
  },
  {
   "title": "Letzte durchgeführte Transaktions-ID",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "(id)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_neo4j_transaction_last_committed_tx_id_total{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}"
    }
   ]
  },
  {
   "title": "Aktive Transaktionen",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "transactions" } },
   "targets": [
    {
     "expr": "neo4j_neo4j_transaction_active_read{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
     "legendFormat": "read"
    },
    {
     "expr": "neo4j_neo4j_transaction_active_write{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Neo4j - JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Nutzung",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "neo4j_vm_memory_pool_g1_eden_space{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "eden space"
      },
      {
       "expr": "sum({__name__=~\"neo4j_vm_memory_pool_g1_(eden_space|old_gen)\", job=\"Neo4j-prometheus\", instance=~\"host.docker.internal:2004\"}) by (instance)",
       "legendFormat": "total"
      },
      {
       "expr": "neo4j_vm_memory_pool_g1_old_gen{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "old gen"
      }
     ]
    },
    {
     "title": "JVM Buffer Nutzung",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "neo4j_vm_memory_buffer_direct_used{instance=\"host.docker.internal:2004\", job=\"Neo4j-prometheus\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neo4j - Speicherauslastung ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    { "title": "Verfügbarer Gesamtspeicher", "type": "timeseries", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 } },
    { "title": "Speicher DEV", "type": "timeseries", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 } },
    { "title": "Speicher INT", "type": "timeseries", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 } },
    { "title": "Speicher PROD", "type": "timeseries", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 } }
   ]
  },
  {
   "title": "Datenübertragung/Durchsatz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "repeat": "priority",
   "collapsed": true,
   "panels": [
    {
     "title": "Logs from Metrics Analyser",
     "type": "logs",
     "gridPos": { "h": 26, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "{agent=\"promtail\"}"
      }
     ]
    },
    {
     "title": "Error Logs from Metric Analyser",
     "type": "logs",
     "gridPos": { "h": 26, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "{agent=\"promtail\" }  |~ \"(?i)error\""
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter Statistiken",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "scrapes" } },
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$instance\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert for Structure Cube",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": " up{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration Structure Cube",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(probe_http_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"}) by(phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Probe Duration Structure Cube",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(probe_duration_seconds{})by(instance) ",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Avg Probe Duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=\"https://hr-ideascape.app.corpintra.net/structurecube/#/\"})"
      }
     ]
    }
   ]
  }
 ]
}